export const orderDetailsStatusName: {
    [key: string]: { name: string; status: 'pending' | 'action' | 'success' | 'error' | 'default' | 'closed' };
} = {
    // Client status
    QUOTATION_CLIENT: { name: 'Order draft', status: 'default' },
    OFFER_CLIENT: { name: 'Waiting offers', status: 'pending' },
    WAITING_TRANSPORT_CLIENT: { name: 'Waiting booking', status: 'pending' },
    CONFIRM_BOOKING_CLIENT: { name: 'Confirm booking', status: 'action' },
    WAITING_CONFIRM_TRANSPORT_EXECUTOR: { name: 'Confirm booking', status: 'action' },
    CONFIRM_TRANSPORT_FROM_AS_CLIENT: { name: 'Confirm booking', status: 'action' },
    PAYMENT_ADVANCE_CLIENT: { name: 'Make payment', status: 'action' },
    WAITING_PAYMENT_ADVANCE_CLIENT: { name: 'Waiting confirmation', status: 'pending' },
    WAITING_SC_CLIENT: { name: 'Activate order', status: 'action' },
    PENDING_SC_CLIENT: { name: 'Waiting activation', status: 'pending' },
    PENDING_TRACKING_CLIENT: { name: 'Preparing transport', status: 'pending' },
    TRACKING_CLIENT_DEMO: { name: 'Tacking', status: 'success' },
    PAYMENT_AFTER_CLIENT: { name: 'Delivery payment', status: 'action' },
    FINISHED_CLIENT_DEMO: { name: 'Closed', status: 'closed' },
    // Old client statuses
    FINISHED_CLIENT: { name: 'Closed', status: 'closed' },
    TRACKING_CLIENT: { name: 'Tracking', status: 'success' },
    PENDING_CLIENT: { name: 'Preparing transport', status: 'pending' },
    WAITING_CONFIRM_CLIENT: { name: 'Waiting confirmation', status: 'pending' },
    INVOICE_CLIENT: { name: 'Make payment', status: 'action' },
    BOOKING_CLIENT: { name: 'Sender & Receiver', status: 'action' },

    // Carrier statuses
    VIEW_EXECUTOR: { name: 'Order draft', status: 'action' },
    OFFER_EXECUTOR: { name: 'Pending', status: 'pending' },
    ACCEPTED_EXECUTOR_CARRIER: { name: 'Pending', status: 'pending' },
    CHOSE_TRANSPORT_CARRIER: { name: 'Provide Booking', status: 'action' },
    CHOSE_TRANSPORT_FROM_AS_CARRIER: { name: 'Provide Booking', status: 'action' },
    REJECT_NOT_ACCEPTED_EXECUTOR_CARRIER: { name: 'Was not accepted', status: 'error' },
    WAITING_CONFIRM_TRANSPORT_CARRIER: { name: 'Pending', status: 'pending' },
    WAITING_PAYMENT_ADVANCE_EXECUTOR: { name: 'Pending', status: 'pending' },
    CONFIRM_PAYMENT_ADVANCE_EXECUTOR: { name: 'Confirm payment', status: 'action' },
    PENDING_SC_CARRIER: { name: 'Pending', status: 'pending' },
    PENDING_TRACKING_CARRIER: { name: 'Pending', status: 'pending' },
    TRACKING_CARRIER_DEMO: { name: 'Tracking', status: 'success' },
    CONFIRM_PAYMENT_EXECUTOR: { name: 'Pending', status: 'pending' },
    FINISHED_CARRIER_DEMO: { name: 'Closed', status: 'closed' },
    // Old carrier statuses
    VIEW_CARRIER: { name: 'Pending', status: 'pending' },
    IN_WORK_CARRIER: { name: 'Pending', status: 'pending' },
    IN_WORK_EXECUTOR: { name: 'Pending', status: 'pending' },
    REJECT_VIEW_CARRIER: { name: 'Was not accepted', status: 'error' },
    OFFER_CARRIER: { name: 'Pending', status: 'pending' },
    REJECT_NOT_ACCEPTED_EXPEDITOR_CARRIER: { name: 'Was not accepted', status: 'error' },
    ACCEPTED_CLIENT_CARRIER: { name: 'Pending', status: 'pending' },
    REJECT_NOT_ACCEPTED_CLIENT_CARRIER: { name: 'Was not accepted', status: 'error' },
    PENDING_CARRIER: { name: 'Pending', status: 'pending' },
    TRACKING_CARRIER: { name: 'Tracking', status: 'success' },
    FINISHED_CARRIER: { name: 'Closed', status: 'closed' },
};
